version: 2.1
orbs:
  synthetics-ci-orb: datadog/synthetics-ci-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &all-branches-and-tags
  tags:
    only: /.*/

jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-simple:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - synthetics-ci-orb/run-tests:
          fail_on_critical_errors: true
  integration-test-with-spaces:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - synthetics-ci-orb/run-tests:
          fail_on_critical_errors: true
          files: |
            ci/file with space.json
            ci/file, with comma.json
  integration-test-with-multiple-public-ids:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - synthetics-ci-orb/run-tests:
          config_path: ci/global.config.json
          fail_on_critical_errors: true
          public_ids: |
            pwd-mwg-3p5
            2r9-q7u-4nn

workflows:
  test-deploy:
    jobs:
      - integration-test-simple:
          filters: *all-branches-and-tags
      - integration-test-with-spaces:
          filters: *all-branches-and-tags
      - integration-test-with-multiple-public-ids:
          filters: *all-branches-and-tags
      - orb-tools/pack:
          filters: *all-branches-and-tags

      # Publish a production version of the orb.
      - orb-tools/publish:
          orb-name: datadog/synthetics-ci-orb
          vcs-type: << pipeline.project.type >>
          context: orb-publishing # A restricted context containing private publishing credentials. Will only execute if approved by an authorized user.
          pub-type: production
          enable-pr-comment: false
          requires:
            - integration-test-simple
            - integration-test-with-spaces
            - integration-test-with-multiple-public-ids
            - orb-tools/pack
          # Run only for semantic tags
          # https://circleci.com/docs/workflows/#executing-workflows-for-a-git-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
